remove version check from selecta and tweak wording in install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 if [ ! "$(ruby -e 'puts RUBY_VERSION >= "1.9.3"' 2>/dev/null)" = "true" ]; then
-  echo "Selecta requires Ruby 1.9.3 or greater." >&2
+  echo "error: Selecta requires Ruby 1.9.3 or higher." >&2
   exit 1
 fi
 
@@ -13,7 +13,10 @@ BIN_DIR="${PREFIX:-/usr/local}/bin"
 
 mkdir -p "$BIN_DIR"
 
-echo "#!$RUBY_PATH --disable-gem" | cat - "$(dirname "$0")/selecta" > "$BIN_DIR/selecta"
+(
+  echo "#!$RUBY_PATH --disable-gem"
+  tail -n +2 "$(dirname "$0")/selecta" 
+) > "$BIN_DIR/selecta"
 
 chmod +x "$BIN_DIR/selecta"
 
